import { ContentType } from "./restApiSchema/contentType.js";

type EmptyPathParameters = {
  query?: never;
  header?: never;
  path?: never;
  cookie?: never;
};

/**
 * This file must follow the format of the schema generated by `openapi-typescript`
 * See ../open-api/schema.ts
 */
export interface paths {
  "/contenttypes": {
    parameters: EmptyPathParameters;
    post: operations["ContentTypes_Create"];
    get: {
      parameters: {};
      requestBody: never;
      responses: {
        200: {
          headers: {};
          content: {
            "application/json": {};
          };
        };
      };
    };
  };
  "/oauth/token": {
    paramters: EmptyPathParameters;
    post: {
      parameters: EmptyPathParameters;
      requestBody: {
        content: {
          "application/json": {
            grant_type: "client_credentials";
            client_id: string;
            client_secret: string;
            act_as?: string;
          };
        };
      };
      responses: {
        200: {
          content: {
            "application/json": {
              access_token: string;
              expires_in?: number;
              token_type?: string;
            };
          };
        };
      };
    };
  };
  "/packages": {
    get: operations["Packages_Export"];
    post: operations["Packages_Import"];
  };
}

export interface operations {
  ContentTypes_Create: {
    requestBody: {
      content: {
        "application/json": ContentType;
      };
    };
  };

  Packages_Export: {};
  Packages_Import: {};
}
